{% set version = "2.2-10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-traminer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TraMineR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TraMineR/TraMineR_{{ version }}.tar.gz
  sha256: 8b1689fe6a0f4ff3493e6b430592705be34f12ac6a24aae1735e5262e50e85a6

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - r-vegan                    # [build_platform != target_platform]
    - r-colorspace               # [build_platform != target_platform]
    - r-rcolorbrewer             # [build_platform != target_platform]
    - r-boot                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-boot
    - r-cluster
    - r-colorspace
    - r-vegan
  run:
    - r-base
    - r-rcolorbrewer
    - r-boot
    - r-cluster
    - r-colorspace
    - r-vegan

test:
  commands:
    - $R -e "library('TraMineR')"           # [not win]
    - "\"%R%\" -e \"library('TraMineR')\""  # [win]

about:
  home: http://traminer.unige.ch
  license: GPL-2.0-or-later
  summary: Toolbox for the manipulation, description and rendering of sequences, and more generally the mining of sequence data in the field of social sciences. Although the toolbox is primarily intended for analyzing state or event sequences that describe life courses such as family formation histories or professional careers,
    its features also apply to many other kinds of categorical sequence data. It accepts many different sequence representations as input and provides tools for converting sequences from one format to another. It offers several functions for describing and rendering sequences, for computing distances between sequences with
    different metrics (among which optimal matching), original dissimilarity-based analysis tools, and simple functions for extracting the most frequent subsequences and identifying the most discriminating ones among them. A user's guide can be found on the TraMineR web page.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: TraMineR
# Version: 2.2-0.1
# Date: 2020-04-29
# Title: Trajectory Miner: a Toolbox for Exploring and Rendering Sequences
# Authors@R: c( person("Alexis", "Gabadinho", role = c("aut", "cph")), person("Matthias", "Studer", role = c("aut", "cph"), comment = c(ORCID = "0000-0002-6269-1412")), person("Nicolas", "Muller", role = "aut"), person("Reto", "Burgin", role = "aut"), person("Pierre-Alexandre", "Fonta", role = "aut"), person("Gilbert", "Ritschard", role = c("aut", "cre", "cph"), email = "gilbert.ritschard@unige.ch", comment = c(ORCID = "0000-0001-7776-0903")))
# Depends: R (>= 3.0.0)
# Imports: utils, RColorBrewer, boot, graphics, grDevices, stats, Hmisc, cluster, colorspace
# Suggests: xtable
# SystemRequirements: C++11
# Description: Toolbox for the manipulation, description and rendering of sequences, and more generally the mining of sequence data in the field of social sciences. Although the toolbox is primarily intended for analyzing state or event sequences that describe life courses such as family formation histories or professional careers, its features also apply to many other kinds of categorical sequence data. It accepts many different sequence representations as input and provides tools for converting sequences from one format to another. It offers several functions for describing and rendering sequences, for computing distances between sequences with different metrics (among which optimal matching), original dissimilarity-based analysis tools, and simple functions for extracting the most frequent subsequences and identifying the most discriminating ones among them. A user's guide can be found on the TraMineR web page.
# License: GPL (>= 2)
# URL: http://traminer.unige.ch
# Encoding: UTF-8
# Maintainer: Gilbert Ritschard <gilbert.ritschard@unige.ch>
# NeedsCompilation: yes
# Packaged: 2020-04-29 15:28:33 UTC; adm
# Author: Alexis Gabadinho [aut, cph], Matthias Studer [aut, cph] (<https://orcid.org/0000-0002-6269-1412>), Nicolas Muller [aut], Reto Burgin [aut], Pierre-Alexandre Fonta [aut], Gilbert Ritschard [aut, cre, cph] (<https://orcid.org/0000-0001-7776-0903>)
# Repository: CRAN
# Date/Publication: 2020-04-29 16:40:14 UTC
